export const RECEIVE_ADDRESS = 'receive_address' // 接收地址信息
export const RECEIVE_CATEGORYS = 'receive_categorys' // 接收分类数组
export const RECEIVE_SHOPS = 'receive_shops' // 接收商家数组
export const RECEIVE_USER = 'receive_user' // 接收商家数组
export const RESET_USER = 'reset_user' // 退出登录
export const RECEIVE_GOODS = 'receive_goods' // 获取商家信息
export const RECEIVE_RATINGS = 'receive_ratings' // 获取商家信息
export const RECEIVE_INFO = 'receive_info' // 获取商家信息
export const INCREMENT_FOOD_COUNT = "increment_food_count" //增加食品数量
export const DECREMENT_FOOD_COUNT = "decrement_food_count" //减少食品数量
export const CLEARFOOD = "clearfood" //清除购物车里面的food
